### ISSUE TITLE
Proposal - Create a MKDocs Site instead of a readme MD file. 

### ISSUE THREAD

**Issue by sidx64** [IDKJUSTPUTSOMETHINGHERE/IMKC-Docs#2]
Proposal - Create a MKDocs Site instead of a readme MD file. 

Would love to take this task up, if there's any interest.

**Comment by lokwaniyash** [comment]
Hey @sidx64, we don't have a very diverse documentation that I think it'd be worth moving to such a documentation solution, although we'll try and keep adding stuff here, and we are looking for something that'd be more easier to set up and contribute, appreciate your proposal <3
